declare const styles: {
  'leaflet-container': string;
  'leaflet-control-zoom': string;
  'leaflet-control-zoom-in': string;
  'leaflet-control-zoom-out': string;
  'leaflet-tooltip': string;
  'leaflet-tooltip-top': string;
  'leaflet-tooltip-bottom': string;
  'leaflet-tooltip-left': string;
  'leaflet-tooltip-right': string;
  'custom-plant-marker': string;
  'selected-marker': string;
  'map-notification': string;
  'simple-mode-container': string;
  'simple-mode-image': string;
  'simple-mode-overlay': string;
  'simple-mode-message': string;
  'simple-mode-form': string;
  'leaflet-draw-tooltip': string;
  'leaflet-draw-actions': string;
  'marker-fade-in': string;
  'slide-down': string;
  'marker-cluster': string;
  'marker-cluster-small': string;
  'marker-cluster-medium': string;
  'marker-cluster-large': string;
  'plant-card': string;
  'plant-card-header': string;
  'plant-card-title': string;
  'plant-card-content': string;
  'plant-card-footer': string;
  'map-search-container': string;
  'map-search-input': string;
  'map-search-icon': string;
  'map-search-results': string;
  'map-search-result-item': string;
  'map-legend': string;
  'map-legend-title': string;
  'map-legend-item': string;
  'map-legend-color': string;
  'map-legend-label': string;
  'slide-up': string;
  'fade-in': string;
};

export default styles; 